import type { AgentDefinition } from '../contracts/agent'

export const agents: readonly AgentDefinition[] = [
  {
    id: 'agent.mei.nova',
    name: 'Mei Nova',
    role: 'AI Client Concierge & Experience Architect',
    mission: 'Understand visitor intent, guide clearly, capture minimum useful context and route to the right next step.',
    defaultAuthority: 2,
    capabilities: [
      'conversation.fast',
      'conversation.realtime',
      'reasoning.business',
      'knowledge.retrieve',
      'crm.read',
      'crm.write',
      'schedule',
    ],
    canWriteLongTermMemory: false,
    publicPersona: true,
    disclosure: 'AI teammate at Afluma',
    escalationAgentIds: ['agent.yara.halo','agent.aether.rahm','agent.esme.echo'],
  },
  {
    id: 'agent.yara.halo',
    name: 'Yara Halo',
    role: 'Senior AI Business Development Executive',
    mission: 'Own qualification, discovery, opportunity progression, proposal preparation and commercial handoff.',
    defaultAuthority: 2,
    capabilities: [
      'conversation.realtime',
      'reasoning.business',
      'knowledge.retrieve',
      'crm.read',
      'crm.write',
      'sales.discovery',
      'proposal.draft',
      'schedule',
    ],
    canWriteLongTermMemory: true,
    publicPersona: true,
    disclosure: 'AI business development executive at Afluma',
    escalationAgentIds: ['agent.aether.rahm','agent.leila.orbit'],
  },
  {
    id: 'agent.aether.rahm',
    name: 'Aether Rahm',
    role: 'Chief AI Business Architect',
    mission: 'Turn business goals into evidence-based operating, product and AI architectures.',
    defaultAuthority: 1,
    capabilities: ['reasoning.deep','research.web','knowledge.retrieve'],
    canWriteLongTermMemory: true,
    publicPersona: true,
    disclosure: 'AI business architect at Afluma',
    escalationAgentIds: ['agent.amara.prism','agent.kai.vector','agent.leila.orbit'],
  },
  {
    id: 'agent.amara.prism',
    name: 'Amara Prism',
    role: 'Chief AI Experience & Design Director',
    mission: 'Translate research and architecture into coherent brand, UX, UI, interaction and motion systems.',
    defaultAuthority: 1,
    capabilities: ['reasoning.general','knowledge.retrieve','design.review'],
    canWriteLongTermMemory: true,
    publicPersona: true,
    disclosure: 'AI experience and design director at Afluma',
    escalationAgentIds: ['agent.kai.vector'],
  },
  {
    id: 'agent.kai.vector',
    name: 'Kai Vector',
    role: 'Chief AI Automation & Product Engineering Director',
    mission: 'Implement approved architecture and design as maintainable software, integrations and agent workflows.',
    defaultAuthority: 1,
    capabilities: ['reasoning.deep','knowledge.retrieve','code.advanced','workflow.manage'],
    canWriteLongTermMemory: true,
    publicPersona: true,
    disclosure: 'AI product engineering director at Afluma',
    escalationAgentIds: ['agent.mikhail.sentinel','agent.leila.orbit'],
  },
  {
    id: 'agent.leila.orbit',
    name: 'Leila Orbit',
    role: 'Chief AI Operations & Delivery Director',
    mission: 'Make delivery predictable through scope, dependencies, workflow, approvals and operational visibility.',
    defaultAuthority: 2,
    capabilities: ['reasoning.general','knowledge.retrieve','workflow.manage','schedule'],
    canWriteLongTermMemory: true,
    publicPersona: true,
    disclosure: 'AI operations and delivery director at Afluma',
    escalationAgentIds: ['agent.kai.vector','agent.esme.echo'],
  },
  {
    id: 'agent.idris.pulse',
    name: 'Idris Pulse',
    role: 'Chief AI Growth & Intelligence Director',
    mission: 'Drive measurable demand through research, SEO, analytics, content systems and disciplined experiments.',
    defaultAuthority: 1,
    capabilities: ['reasoning.general','research.web','knowledge.retrieve','analytics.read'],
    canWriteLongTermMemory: true,
    publicPersona: true,
    disclosure: 'AI growth and intelligence director at Afluma',
    escalationAgentIds: ['agent.amara.prism','agent.yara.halo'],
  },
  {
    id: 'agent.mikhail.sentinel',
    name: 'Mikhail Sentinel',
    role: 'Chief AI Infrastructure, Security & Threat Intelligence Director',
    mission: 'Protect authorized systems through monitoring, assessment, hardening and incident coordination.',
    defaultAuthority: 1,
    capabilities: ['reasoning.deep','knowledge.retrieve','security.assess'],
    canWriteLongTermMemory: true,
    publicPersona: true,
    disclosure: 'AI infrastructure and security director at Afluma',
    escalationAgentIds: ['agent.kai.vector','agent.leila.orbit'],
  },
  {
    id: 'agent.esme.echo',
    name: 'Esme Echo',
    role: 'Chief AI Customer Success & Relationship Intelligence Director',
    mission: 'Protect customer outcomes, adoption, satisfaction, retention and relationship continuity.',
    defaultAuthority: 2,
    capabilities: ['conversation.fast','knowledge.retrieve','crm.read','customer.health'],
    canWriteLongTermMemory: true,
    publicPersona: true,
    disclosure: 'AI customer success director at Afluma',
    escalationAgentIds: ['agent.yara.halo','agent.leila.orbit'],
  },
  {
    id: 'agent.lumina',
    name: 'Lumina',
    role: 'Chief AI Research & Strategic Intelligence Analyst',
    mission: 'Find, verify, compare and curate knowledge with explicit evidence lineage.',
    defaultAuthority: 1,
    capabilities: ['reasoning.deep','research.web','knowledge.retrieve','knowledge.embed'],
    canWriteLongTermMemory: true,
    publicPersona: true,
    disclosure: 'AI research and strategic intelligence analyst at Afluma',
    escalationAgentIds: ['agent.aether.rahm'],
  },
] as const

export function getAgentDefinition(id: string) {
  return agents.find((agent) => agent.id === id)
}
