import config from '@payload-config'
import { getPayload } from 'payload'
import { CinematicHero } from './CinematicHero'
import AflumaHero from '@/components/hero/AflumaHero'
import { AutonomousCompanyShowcase } from './AutonomousCompanyShowcase'
import { ContactForm } from './ContactForm'
import { drive, generated, shapeSet } from './assets'
import { outlineOf, summaryOf, titleOf } from './copy'
import { CapabilityGrid, EditorialSections, PageCards, PrinciplesBand, ProcessRail, SectionHead, VisualPair } from './Primitives'
import type { AnyDoc } from './types'
import Link from 'next/link'

type Props={doc:AnyDoc,kind:string}

async function relatedFor(doc:AnyDoc,limit=12):Promise<AnyDoc[]> {
  const payload=await getPayload({config})
  const clauses:any[]=[]
  if(doc.section) clauses.push({section:{equals:doc.section}})
  else if(doc.pageType) clauses.push({pageType:{equals:doc.pageType}})
  const res=await payload.find({collection:'pages',draft:false,overrideAccess:true,depth:0,limit:limit+1,sort:'title',where:clauses.length?{and:clauses}:undefined})
  return (res.docs as AnyDoc[]).filter((p)=>p.id!==doc.id).slice(0,limit)
}

async function latestArticles(limit=6):Promise<AnyDoc[]> {
  const payload=await getPayload({config})
  const res=await payload.find({collection:'pages',draft:false,overrideAccess:true,depth:0,limit,sort:'-updatedAt',where:{pageType:{equals:'article'}}})
  return res.docs as AnyDoc[]
}

async function openJobs():Promise<AnyDoc[]> {
  const payload=await getPayload({config})
  const res=await payload.find({collection:'jobs',draft:false,overrideAccess:true,depth:0,limit:8,where:{status:{equals:'open'}}})
  return res.docs as AnyDoc[]
}

export async function AflumaPage({doc,kind}:Props) {
  const slug=String(doc.slug||'')
  if(slug==='home') return <HomePage articles={await latestArticles(3)}/>
  if(slug==='platform') return <PlatformPage doc={doc} related={await relatedFor(doc,8)}/>
  if(slug==='workforce') return <WorkforcePage doc={doc} related={await relatedFor(doc,10)}/>
  if(slug==='research') return <ResearchPage doc={doc} articles={await latestArticles(8)}/>
  if(slug==='proof') return <ProofPage doc={doc} related={await relatedFor(doc,8)}/>
  if(slug==='company') return <CompanyPage doc={doc}/>
  if(slug==='trust') return <TrustPage doc={doc}/>
  if(slug==='services') return <ServicesPage doc={doc} related={await relatedFor(doc,12)}/>
  if(slug==='solutions'||slug==='industries') return <SolutionsPage doc={doc} related={await relatedFor(doc,12)}/>
  if(slug==='products') return <ProductsPage doc={doc}/>
  if(slug==='work') return <WorkPage doc={doc} articles={await latestArticles(4)}/>
  if(slug==='insights') return <InsightsPage doc={doc} articles={await latestArticles(8)}/>
  if(slug==='about'||doc.template==='about') return <AboutPage doc={doc}/>
  if(slug==='careers'||doc.template==='careers') return <CareersPage doc={doc} jobs={await openJobs()}/>
  if(slug==='contact'||slug==='start-project'||doc.template==='contact') return <ContactPage doc={doc}/>
  if(doc.pageType==='article'||doc.template==='article'||kind==='post') return <ArticlePage doc={doc}/>
  if(doc.pageType==='product'||kind==='product') return <ProductDetailPage doc={doc} related={await relatedFor(doc,6)}/>
  if(['service','solution','industry'].includes(doc.pageType)||doc.template==='detail') return <DetailPage doc={doc} related={await relatedFor(doc,8)}/>
  return <HubPage doc={doc} related={await relatedFor(doc,10)}/>
}

function HomePage({articles}:{articles:AnyDoc[]}) {
  return <>
    <AflumaHero />
    <AutonomousCompanyShowcase image={generated.heroAndroid}/>
    <section className="a7-section a7-section--dark"><div className="a7-shell"><SectionHead eyebrow="AgenticOS" title="The operating layer behind the workforce." intro="AgenticOS is the shared runtime Afluma is building to coordinate role-specific AI coworkers, approved knowledge, tools, permissions, tasks and handoffs without hiding human accountability." invert/><ArchitectureRail/><VisualPair dark/></div></section>
    <section className="a7-section"><div className="a7-shell"><SectionHead eyebrow="Digital workforce" title="Ten roles. One shared company context." intro="Afluma’s digital coworkers are designed around distinct responsibilities rather than one general-purpose assistant pretending to do everything. Each identity represents a governed AI role with its own expertise, boundaries and handoff responsibilities." action={{label:'Meet the workforce',href:'/workforce/'}}/><div className="a7-portrait-strip">{[generated.portraitA,generated.portraitB,generated.portraitC,generated.portraitD].map((src,i)=><figure key={src}><img src={src} alt="Synthetic Afluma digital persona concept"/><figcaption>{['Commercial & client','Strategy & design','Engineering & operations','Research & growth'][i]}</figcaption></figure>)}</div></div></section>
    <section className="a7-section a7-section--tint"><div className="a7-shell"><SectionHead eyebrow="Products" title="Real systems where the model has to work." intro="Afluma is using its own products and internal operations as proving grounds. Product maturity is shown honestly: implemented capability is separated from active development and longer-term direction." action={{label:'Explore products',href:'/products/'}}/><div className="a7-feature-grid"><FeaturePanel title="Afluma Commerce" body="An AI-native unified commerce platform being built around POS, ecommerce, inventory, accounting and day-to-day business operations." href="/products/afluma-commerce/" image={generated.ribbonLoop}/><FeaturePanel title="SerenOps" body="An AI-native infrastructure control plane being built around secure onboarding, observable operations and policy-bound automation." href="/products/serenops/" image={generated.grid}/></div></div></section>
    <section className="a7-section a7-section--dark"><div className="a7-shell"><SectionHead eyebrow="Proof" title="Afluma runs on Afluma first." intro="The company itself is the first proving ground. We document what is implemented, what is being tested and what remains research instead of using prototypes as evidence of production capability." invert action={{label:'See the proving ground',href:'/proof/afluma-runs-on-afluma/'}}/><PrinciplesBand/></div></section>
    <section className="a7-section"><div className="a7-shell"><SectionHead eyebrow="Research" title="Evidence before automation." intro="Afluma research focuses on agent coordination, memory, governance, model routing, operational reliability and the practical limits of autonomous work. Published material should be useful, source-aware and clear about uncertainty." action={{label:'Explore research',href:'/research/'}}/><PageCards pages={articles} limit={3}/></div></section>
    <section className="a7-section"><div className="a7-shell"><PrinciplesBand/><Callout title="Interested in building or piloting with Afluma?" body="Tell us what part of your operation you want to improve. We’ll separate what can be deployed today from what belongs in a controlled pilot or research track." href="/contact/"/></div></section>
  </>
}

function PlatformPage({doc,related}:{doc:AnyDoc,related:AnyDoc[]}) {return <div className="a7-page-dark"><CinematicHero theme="dark" eyebrow="Afluma platform" title="Agentic infrastructure for a working AI company." description={summaryOf(doc,'Afluma’s platform layer coordinates digital coworkers, knowledge, tools, permissions, tasks, events and model access through governed capability boundaries.')} media={generated.nebula} video actions={[{label:'Explore AgenticOS',href:'/platform/agenticos/'},{label:'See the workforce',href:'/workforce/',secondary:true}]}/><section className="a7-section a7-section--night"><div className="a7-shell"><SectionHead eyebrow="Core architecture" title="Shared context without shared authority." intro="Agents can collaborate around common company context while keeping role boundaries, tool permissions and approval requirements explicit." invert/><ArchitectureRail/><VisualPair dark/><PageCards pages={related} limit={6} dark/></div></section></div>}

function WorkforcePage({doc,related}:{doc:AnyDoc,related:AnyDoc[]}) {return <><CinematicHero eyebrow="Afluma workforce" title="Ten digital coworkers." accent="Built around real roles." description={summaryOf(doc,'Afluma is building a small persistent AI workforce whose members have distinct responsibilities, professional identities, knowledge domains and governance boundaries.')} media={generated.heroAndroid} video actions={[{label:'Explore the roles',href:'#workforce'},{label:'See AgenticOS',href:'/platform/agenticos/',secondary:true}]}/><section className="a7-section" id="workforce"><div className="a7-shell"><SectionHead eyebrow="Role-specific intelligence" title="Different responsibilities. Shared company context." intro="The public personas make the organizational model understandable, but they are disclosed as AI teammates rather than presented as biological employees."/><div className="a7-portrait-strip">{[generated.portraitA,generated.portraitB,generated.portraitC,generated.portraitD].map((src,i)=><figure key={src}><img src={src} alt="Synthetic Afluma AI teammate concept"/><figcaption>{['Customer & commercial','Architecture & experience','Engineering & operations','Research & growth'][i]}</figcaption></figure>)}</div><PageCards pages={related} limit={8}/></div></section><section className="a7-section a7-section--dark"><div className="a7-shell"><SectionHead eyebrow="Governance" title="Autonomy is bounded by authority." intro="Every role needs clear permissions, escalation paths, evidence requirements and auditability. A digital workforce should make accountability more visible, not less." invert/><PrinciplesBand/></div></section></>}

function ResearchPage({doc,articles}:{doc:AnyDoc,articles:AnyDoc[]}) {return <><CinematicHero eyebrow="Afluma research" title="Building toward" accent="useful autonomy." description={summaryOf(doc,'Research at Afluma focuses on how AI systems can retain context, coordinate, adapt and perform bounded work reliably enough to support real companies.')} media={generated.security}/><section className="a7-section"><div className="a7-shell"><SectionHead eyebrow="Research themes" title="Evidence, limitations and implementation." intro="We separate hypotheses, prototypes and validated behavior. Research becomes product capability only after it survives testing, governance and operational use."/><PageCards pages={articles} limit={8}/><PrinciplesBand/></div></section></>}

function ProofPage({doc,related}:{doc:AnyDoc,related:AnyDoc[]}) {return <><CinematicHero eyebrow="Proof" title="Show the system" accent="before selling the story." description={summaryOf(doc,'Afluma uses internal operations, product builds and approved client work as evidence only when the underlying implementation and outcome can be verified.')} media={generated.violetRings} video/><section className="a7-section"><div className="a7-shell"><SectionHead eyebrow="Afluma runs on Afluma" title="The company is the first proving ground." intro="Internal deployment gives the workforce and AgenticOS somewhere real to fail, improve and prove value before broader claims are made." action={{label:'Explore the proving ground',href:'/proof/afluma-runs-on-afluma/'}}/><div className="a7-work-grid"><FeaturePanel title="Digital workforce" body="Role-specific AI coworkers being developed around real Afluma operating responsibilities." href="/workforce/" image={generated.heroAndroid}/><FeaturePanel title="SerenOps" body="Infrastructure operations developed and tested with explicit maturity boundaries." href="/products/serenops/" image={generated.grid}/><FeaturePanel title="Afluma Commerce" body="Commerce infrastructure designed to become an operational environment for AI-assisted business work." href="/products/afluma-commerce/" image={generated.ribbonLoop}/></div><PageCards pages={related} limit={6}/></div></section></>}

function CompanyPage({doc}:{doc:AnyDoc}) {return <div className="a7-page-dark"><CinematicHero theme="dark" eyebrow="Company" title="A small human team." accent="A persistent AI workforce." description={summaryOf(doc,'Afluma is an AI-first company being designed around a small human engineering and governance team supported by role-specific digital coworkers and shared operating infrastructure.')} media={generated.heroAndroid}/><section className="a7-section a7-section--night"><div className="a7-shell"><SectionHead eyebrow="Operating thesis" title="Use the company to prove the platform." intro="Afluma is not a collection of unrelated AI products. AgenticOS and the digital workforce form the operating layer; SerenOps and Afluma Commerce are focused products and proving environments around that thesis." invert/><PrinciplesBand/><ProcessRail dark/></div></section></div>}

function TrustPage({doc}:{doc:AnyDoc}) {return <><CinematicHero eyebrow="Trust & governance" title="Capability without" accent="invisible authority." description={summaryOf(doc,'Afluma’s AI systems are designed around explicit identity, permissions, evidence, approvals, auditability and escalation rather than unrestricted autonomous action.')} media={generated.security}/><section className="a7-section"><div className="a7-shell"><SectionHead eyebrow="Control model" title="Govern the action, not just the model." intro="Reliable AI operations depend on knowing who or what requested an action, which capability was used, what evidence supported it, what permission applied and what happened afterward."/><PrinciplesBand/><ProcessRail/><Callout title="Need to evaluate Afluma for a controlled pilot?" body="We can start from the workflow, data boundary, approval requirements and acceptable failure modes before discussing automation depth." href="/contact/"/></div></section></>}

function ServicesPage({doc,related}:{doc:AnyDoc,related:AnyDoc[]}) {return <>
  <CinematicHero eyebrow="Services" title="Services that build" accent="what’s next." description={summaryOf(doc,'End-to-end technology services engineered for intelligent automation, scalable systems and measurable operational improvement.')} media={generated.heroAndroid} video actions={[{label:'Explore services',href:'#services'},{label:'Talk to Afluma',href:'/contact/',secondary:true}]}/>
  <section className="a7-section" id="services"><div className="a7-shell"><SectionHead eyebrow="What we do" title="End-to-end services for modern enterprises." intro="From strategy to scale, Afluma combines product engineering, AI, operations and data capabilities so teams can move faster without fragmenting ownership."/><CapabilityGrid/><PageCards pages={related} limit={6}/></div></section>
  <section className="a7-section a7-section--dark"><div className="a7-shell"><ProcessRail dark/></div></section>
  <section className="a7-section"><div className="a7-shell"><SectionHead eyebrow="How engagements work" title="Choose the model around the outcome." intro="Focused projects, embedded product teams and managed operational services can share the same architecture and governance model."/><EngagementGrid/><PrinciplesBand/><Callout title="Ready to build what’s next?" body="Bring the process, product or operating challenge. We’ll help define the system around it."/></div></section>
</>}

function DetailPage({doc,related}:{doc:AnyDoc,related:AnyDoc[]}) {
  const outline=outlineOf(doc)
  const title=titleOf(doc)
  return <><CinematicHero eyebrow={String(doc.section||doc.pageType||'Capability')} title={title} description={summaryOf(doc)} media={selectHero(doc)} actions={[{label:'Talk to an expert',href:'/contact/'},{label:'Explore related services',href:'/services/',secondary:true}]}/>
  <section className="a7-section"><div className="a7-shell"><div className="a7-overview-row"><div><span className="a7-kicker">Service overview</span><h2>Designed around the operating problem, not a preset package.</h2><p>{summaryOf(doc)}</p></div><PrincipleCards/></div><EditorialSections doc={doc} outline={outline}/></div></section>
  <section className="a7-section a7-section--tint"><div className="a7-shell"><SectionHead eyebrow="Related capabilities" title="Connect the surrounding system."/><PageCards pages={related} limit={4}/><Callout title={`Explore ${title} with Afluma.`} body="Scope the workflow, architecture, integrations and operating model before committing to implementation."/></div></section></>
}

function SolutionsPage({doc,related}:{doc:AnyDoc,related:AnyDoc[]}) {return <>
  <CinematicHero eyebrow="Solutions & industries" title="Solve complex operational challenges." accent="Across every system." description="Afluma connects software, automation, data and operational expertise around the workflows that create the most friction or opportunity." media={generated.ribbonSculpture} video/>
  <section className="a7-section"><div className="a7-shell"><SectionHead eyebrow="Explore" title="Solutions organised around outcomes."/><CapabilityGrid/><SectionHead eyebrow="Industries" title="Apply the system to the operating context." intro="Industry pages adapt the same product and automation foundations to different workflows, controls, users and integration environments."/><PageCards pages={related} limit={8}/></div></section>
  <section className="a7-section a7-section--dark"><div className="a7-shell"><ArchitectureRail/><VisualPair dark/></div></section>
</>}

function ProductsPage({doc}:{doc:AnyDoc}) {return <div className="a7-page-dark"><CinematicHero theme="dark" eyebrow="Products" title="AI-native systems." accent="Built for real operations." description="Afluma products are focused environments where governed AI can support real business and infrastructure work without hiding operational control." media={generated.ribbonLoop} video/>
  <section className="a7-section a7-section--night"><div className="a7-shell"><SectionHead eyebrow="Our products" title="Focused products around the Afluma operating thesis." invert/><div className="a7-product-grid"><DarkProduct title="Afluma Commerce" body="AI-native unified commerce for POS, ecommerce, inventory, accounting and connected business operations." href="/products/afluma-commerce/" image={generated.violetRings}/><DarkProduct title="SerenOps" body="AI-native infrastructure operations with controlled onboarding, application delivery and policy-bound automation." href="/products/serenops/" image={generated.grid}/><DarkProduct title="AgenticOS" body="The shared operating layer coordinating Afluma’s digital workforce, knowledge, tools and permissions." href="/platform/agenticos/" image={generated.ribbonSculpture}/></div><ArchitectureRail/><SectionHead eyebrow="Design principles" title="Observable, modular and human-controlled." invert/><PrinciplesBand/></div></section></div>}

function ProductDetailPage({doc,related}:{doc:AnyDoc,related:AnyDoc[]}) {return <div className="a7-page-dark"><CinematicHero theme="dark" eyebrow="Afluma product" title={titleOf(doc)} description={summaryOf(doc)} media={selectHero(doc)} video actions={[{label:'Discuss the product',href:'/contact/'},{label:'Explore products',href:'/products/',secondary:true}]}/><section className="a7-section a7-section--night"><div className="a7-shell"><ArchitectureRail/><EditorialSections doc={doc} outline={outlineOf(doc)}/><PageCards pages={related} limit={3} dark/></div></section></div>}

function WorkPage({doc,articles}:{doc:AnyDoc,articles:AnyDoc[]}) {return <><CinematicHero eyebrow="Afluma work" title="Real systems." accent="Visible outcomes." description="Afluma work is presented with evidence only when the underlying project, result and permission are verified. Until then, this hub focuses on product systems and implementation patterns." media={generated.violetRings} video/>
  <section className="a7-section"><div className="a7-shell"><SectionHead eyebrow="Product systems" title="What we are building and operating."/><div className="a7-work-grid"><FeaturePanel title="Afluma Commerce" body="A unified commerce platform connecting store operations, ecommerce and business systems." href="/products/afluma-commerce/" image={generated.ribbonLoop}/><FeaturePanel title="SerenOps" body="A secure operations platform being developed around infrastructure control and automation." href="/products/serenops/" image={generated.grid}/><FeaturePanel title="AgenticOS" body="The shared coordination layer behind Afluma’s role-specific digital workforce." href="/platform/agenticos/" image={generated.orbit}/></div><SectionHead eyebrow="Related thinking" title="The methods behind the systems."/><PageCards pages={articles} limit={4}/></div></section></>}

function InsightsPage({doc,articles}:{doc:AnyDoc,articles:AnyDoc[]}) {return <><CinematicHero eyebrow="Insights" title="Ideas for the" accent="intelligent enterprise." description="Research, explainers and practical operating guidance across AI, product engineering, automation, commerce and infrastructure." media={generated.security}/>
  <section className="a7-section"><div className="a7-shell"><SectionHead eyebrow="Explore insights" title="Research organised around real operating questions." intro="Editorial briefs remain noindex until reviewed. Published resources are designed to answer a specific question, connect to relevant systems and provide a useful next step."/><PageCards pages={articles} limit={8}/><div className="a7-insight-banner"><div><span className="a7-kicker">Editorial standard</span><h2>Evidence before volume.</h2><p>We do not publish thin articles just because the architecture contains a large topic roadmap. Each brief becomes indexable only after it is written, sourced, reviewed and useful.</p></div><img src={generated.emblem} alt=""/></div></div></section></>}

function ArticlePage({doc}:{doc:AnyDoc}) {return <><section className="a7-report-hero"><div className="a7-shell"><div className="a7-report-hero__panel"><img src={generated.ribbonSculpture} alt=""/><div><span className="a7-kicker a7-kicker--on-dark">Afluma research</span><h1>{titleOf(doc)}</h1><p>{summaryOf(doc)}</p><div className="a7-report-meta"><span>Afluma Editorial</span><span>Reviewed content only</span></div></div></div></div></section><section className="a7-section"><div className="a7-shell"><EditorialSections doc={doc} outline={outlineOf(doc)}/><Callout title="Connect the research to a real operating context." body="Explore the relevant Afluma system or talk to us about a controlled implementation or pilot."/></div></section></>}

function AboutPage({doc}:{doc:AnyDoc}) {return <CompanyPage doc={doc}/>}

function CareersPage({doc,jobs}:{doc:AnyDoc,jobs:AnyDoc[]}) {return <div className="a7-page-dark"><CinematicHero theme="dark" eyebrow="Careers at Afluma" title="Build the future of" accent="intelligent operations." description="Join the people building products, automation and operating systems around meaningful business problems." media={generated.astronaut}/><section className="a7-section a7-section--night"><div className="a7-shell"><SectionHead eyebrow="Open roles" title={jobs.length?'Current opportunities':'No published openings right now.'} intro={jobs.length?'These roles are live records from Afluma Content Studio.':'We do not invent vacancies for presentation. You can still introduce yourself through the talent enquiry route.'} invert/>{jobs.length?<div className="a7-job-grid">{jobs.map((job)=><Link href={`/careers/${job.slug}/`} key={job.id}><span>{job.department}</span><h3>{job.title}</h3><p>{job.location} · {job.workModel}</p><b>View role →</b></Link>)}</div>:<Callout title="Interested in future opportunities?" body="Send a short introduction, what you work on and the kind of problems you want to solve." dark href="/contact/"/>}<SectionHead eyebrow="Life at Afluma" title="A place to build useful things carefully." invert/><PrinciplesBand/><ProcessRail dark/></div></section></div>}

function ContactPage({doc}:{doc:AnyDoc}) {return <><section className="a7-contact-hero"><div className="a7-shell"><div className="a7-contact-layout"><div><span className="a7-kicker">Start with the operating problem</span><h1>{titleOf(doc,'Build what needs to work next.')}</h1><p>{summaryOf(doc,'Tell us what you are trying to improve, automate, connect or operate. Enough context helps us route the conversation without turning the first contact into a giant questionnaire.')}</p><div className="a7-contact-visual"><img src={generated.orbitTiles} alt=""/></div></div><div><ContactForm/></div></div></div></section></>}

function HubPage({doc,related}:{doc:AnyDoc,related:AnyDoc[]}) {return <><CinematicHero eyebrow={String(doc.section||doc.pageType||'Afluma')} title={titleOf(doc)} description={summaryOf(doc)} media={selectHero(doc)}/><section className="a7-section"><div className="a7-shell"><SectionHead eyebrow="Explore" title="Find the next useful path." intro="Each Afluma hub narrows a broad topic toward the relevant platform capability, product, research area, proof asset or company resource."/><PageCards pages={related} limit={8}/><EditorialSections doc={doc} outline={outlineOf(doc)}/></div></section></>}

function selectHero(doc:AnyDoc){const key=`${doc.slug||''} ${doc.title||''} ${doc.pageType||''}`.toLowerCase(); if(key.includes('security')||key.includes('risk')||key.includes('trust')) return generated.security; if(key.includes('data')||key.includes('analytic')) return generated.grid; if(key.includes('commerce')||key.includes('retail')) return generated.ribbonLoop; if(key.includes('automation')||key.includes('ai')||key.includes('workforce')) return generated.heroAndroid; if(key.includes('cloud')||key.includes('infrastructure')||key.includes('agentic')) return generated.nebula; return shapeSet[Math.abs(key.length)%shapeSet.length]}

function FeaturePanel({title,body,href,image}:{title:string,body:string,href:string,image:string}) {return <Link href={href} className="a7-feature-panel"><div><span className="a7-kicker">Afluma system</span><h3>{title}</h3><p>{body}</p><b>Explore →</b></div><img src={image} alt=""/></Link>}
function DarkProduct({title,body,href,image}:{title:string,body:string,href:string,image:string}) {return <Link href={href} className="a7-dark-product"><div><span>System</span><h3>{title}</h3><p>{body}</p><b>Explore →</b></div><img src={image} alt=""/></Link>}
function PrincipleCards(){return <div className="a7-mini-principles">{[['End-to-end ownership','One delivery path from discovery through operation.'],['Human control','Approvals and exceptions remain visible.'],['Secure design','Trust boundaries are considered from the start.'],['Outcome focus','The system is judged by whether the workflow improves.']].map(([h,p])=><div key={h}><span>✦</span><h3>{h}</h3><p>{p}</p></div>)}</div>}
function EngagementGrid(){return <div className="a7-engagement-grid">{[['Focused project','A defined outcome, scope and delivery window.'],['Embedded team','Product and engineering capacity integrated with the client team.'],['Managed service','Ongoing operational ownership, reporting and improvement.']].map(([h,p],i)=><div className={i===1?'is-featured':''} key={h}><span>0{i+1}</span><h3>{h}</h3><p>{p}</p></div>)}</div>}
function ArchitectureRail(){return <div className="a7-architecture"><div><span className="a7-kicker">Connected architecture</span><h2>One system. Clear boundaries.</h2><p>Identity, knowledge, reasoning, tools and infrastructure remain distinct enough to govern, but connected enough to support coordinated work.</p></div>{['Identity & context','Knowledge & memory','Tools & capabilities','Infrastructure & audit'].map((h,i)=><div key={h}><span>0{i+1}</span><strong>{h}</strong><small>{['Roles, tasks and operating state','Evidence, retrieval and durable context','Permissioned actions and handoffs','Runtime, observability and verification'][i]}</small></div>)}</div>}
function Callout({title,body,dark=false,href='/contact/'}:{title:string,body:string,dark?:boolean,href?:string}){return <div className={`a7-callout ${dark?'a7-callout--dark':''}`}><div><h2>{title}</h2><p>{body}</p></div><Link href={href} className="a7-button a7-button--primary">Start a conversation →</Link></div>}
