export const generated = {
  heroAndroid: '/afluma-v07/generated/hero-android.png',
  violetRings: '/afluma-v07/generated/violet-rings.png',
  grid: '/afluma-v07/generated/grid-blueprint.png',
  interfaceHand: '/afluma-v07/generated/interface-hand.png',
  nebula: '/afluma-v07/generated/nebula.png',
  orbit: '/afluma-v07/generated/orbit-ui.png',
  ribbonLoop: '/afluma-v07/generated/ribbon-loop.png',
  ribbonSculpture: '/afluma-v07/generated/ribbon-sculpture.png',
  security: '/afluma-v07/generated/security-emblem.png',
  iconSystem: '/afluma-v07/generated/icon-system.png',
  portraitA: '/afluma-v07/generated/neon_chrome_android_portrait.png',
  portraitB: '/afluma-v07/generated/neon_chrome_visor_portrait.png',
  portraitC: '/afluma-v07/generated/neon_cyberpunk_cyborg_portrait.png',
  portraitD: '/afluma-v07/generated/neon_cyberpunk_profile_portrait.png',
  astronaut: '/afluma-v07/generated/neon_astronaut_in_a_sunset_orb.png',
  iconTiles: '/afluma-v07/generated/neon_glass_app_icon_tiles.png',
  orbitTiles: '/afluma-v07/generated/neon_hand_and_orbiting_interface_tiles.png',
  emblem: '/afluma-v07/generated/neon_holographic_emblem_held_by_hand.png',
  iconRing: '/afluma-v07/generated/neon_icon_ring_around_purple_logo.png',
} as const

export const drive = {
  motion: '/afluma-v07/drive/tube-dark.mp4',
  shapeA: '/afluma-v07/drive/ns-img-504.png',
  shapeB: '/afluma-v07/drive/ns-img-509.png',
  shapeC: '/afluma-v07/drive/ns-img-510.png',
  shapeD: '/afluma-v07/drive/ns-img-515.png',
  shapeE: '/afluma-v07/drive/ns-img-516.png',
  shapeF: '/afluma-v07/drive/ns-img-520.png',
  shapeG: '/afluma-v07/drive/ns-img-521.png',
  shapeH: '/afluma-v07/drive/ns-img-522.png',
  shapeI: '/afluma-v07/drive/ns-img-523.png',
  shapeJ: '/afluma-v07/drive/ns-img-533.png',
  shapeK: '/afluma-v07/drive/ns-img-539.png',
  interface: '/afluma-v07/drive/ns-img-368.png',
  collaborationA: '/afluma-v07/drive/ns-img-397.png',
  collaborationB: '/afluma-v07/drive/ns-img-398.png',
} as const

export const shapeSet = [
  drive.shapeA,
  drive.shapeB,
  drive.shapeC,
  drive.shapeD,
  drive.shapeE,
  drive.shapeF,
  drive.shapeG,
  drive.shapeH,
  drive.shapeI,
  drive.shapeJ,
  drive.shapeK,
]
