import Link from 'next/link'
import { MediaAsset } from './Media'

const action = (item: any, key = '') => item?.label && item?.href ? <Link key={key || item.href} className={`button ${item.style || 'primary'}`} href={item.href}>{item.label}<span>→</span></Link> : null

export function RenderBlocks({ blocks = [] }: { blocks?: any[] }) {
  return <>{blocks.map((block, index) => {
    const key = `${block.blockType}-${block.id || index}`
    if (block.blockType === 'cinematicHero') return <section className="hero section" key={key}><div className="shell"><div className="cinema"><MediaAsset className="cinema-media" media={block.visual?.media} fallback={block.visual?.fallbackAssetPath} alt={block.visual?.alt || ''}/><div className="cinema-overlay"/><div className="cinema-top"><div className="cinema-tabs">{block.tabs?.map((tab:any,i:number)=><span key={i}>{tab.label}</span>)}</div><div className="cinema-tools"><button aria-label="Toggle sound">⌁</button><button aria-label="Pause media">Ⅱ</button></div></div><div className="cinema-copy"><span className="kicker">{block.eyebrow}</span><h1>{block.headline} {block.accentText && <em>{block.accentText}</em>}</h1><p>{block.description}</p><div className="actions">{block.actions?.map((item:any,i:number)=>action(item,String(i)))}</div></div>{block.statusCard?.enabled && <aside className="status-card"><small>{block.statusCard.label}</small><strong>{block.statusCard.value}</strong><p>{block.statusCard.note}</p></aside>}<div className="cinema-bottom">{block.chapters?.map((chapter:any,i:number)=><button className={i===0?'active':''} key={i}><span>0{i+1}</span>{chapter.label}</button>)}</div></div></div></section>
    if (block.blockType === 'editorialIntro') return <section className={`section intro ${block.alignment || ''}`} key={key}><div className="shell"><span className="kicker">{block.eyebrow}</span><h2>{block.heading}</h2><p>{block.body}</p>{action(block.action)}</div></section>
    if (block.blockType === 'bentoGrid') return <section className={`section ${block.theme==='dark'?'night':''}`} key={key}><div className="shell"><span className="kicker">{block.eyebrow}</span><h2>{block.heading}</h2><p className="lede">{block.intro}</p><div className="bento">{block.items?.map((item:any,i:number)=><article className={`card ${item.size || 'medium'}`} key={i}><MediaAsset className="card-media" media={item.media} fallback={item.fallbackAssetPath} alt={item.alt || ''}/><div className="card-body"><span className="icon">{item.iconKey || '↗'}</span><h3>{item.title}</h3><p>{item.body}</p>{action(item.link)}</div></article>)}</div></div></section>
    if (block.blockType === 'capabilityTheatre') return <section className="section night" key={key}><div className="shell"><h2>{block.heading}</h2><p className="lede">{block.intro}</p><div className="capability-theatre">{block.panels?.map((item:any,i:number)=><article key={i}><MediaAsset media={item.media} fallback={item.fallbackAssetPath} alt={item.alt || ''}/><div><span>{item.eyebrow}</span><h3>{item.title}</h3><p>{item.body}</p>{action(item.link)}</div></article>)}</div></div></section>
    if (block.blockType === 'mediaFeature') return <section className="section" key={key}><div className={`shell feature ${block.layout || ''}`}><div><span className="kicker">{block.eyebrow}</span><h2>{block.heading}</h2><p>{block.body}</p>{action(block.action)}</div><MediaAsset media={block.media} fallback={block.fallbackAssetPath} alt={block.alt || ''}/></div></section>
    if (block.blockType === 'process') return <section className="section process" key={key}><div className="shell"><span className="kicker">{block.eyebrow}</span><h2>{block.heading}</h2><p className="lede">{block.intro}</p><div className="process-grid">{block.steps?.map((step:any,i:number)=><article key={i}><span>0{i+1}</span><h3>{step.title}</h3><p>{step.body}</p></article>)}</div></div></section>
    if (block.blockType === 'metrics') return <section className={`section metrics ${block.theme==='dark'?'night':''}`} key={key}><div className="shell"><h2>{block.heading}</h2><div className="metric-grid">{block.items?.filter((item:any)=>item.verified).map((item:any,i:number)=><article key={i}><strong>{item.value}</strong><span>{item.label}</span>{item.source&&<small>{item.source}</small>}</article>)}</div></div></section>
    if (block.blockType === 'cta') return <section className={`section cta ${block.theme || 'dark'}`} key={key}><div className="shell cta-inner"><div><span className="kicker">{block.eyebrow}</span><h2>{block.heading}</h2><p>{block.body}</p><div className="actions">{block.actions?.map((item:any,i:number)=>action(item,String(i)))}</div></div><MediaAsset media={block.media} fallback={block.fallbackAssetPath} alt={block.alt || ''}/></div></section>
    if (block.blockType === 'form') return <section className="section" key={key}><div className="shell form-section"><div><h2>{block.heading}</h2><p>{block.body}</p></div><form action="/api/enquiries" method="post"><input type="hidden" name="enquiryType" value={block.formType==='talent-network'?'career':'project'}/><label>Name<input name="name" required/></label><label>Work email<input type="email" name="email" required/></label><label>Company<input name="company"/></label><label className="full">Message<textarea name="message" required/></label><label className="consent"><input type="checkbox" name="consent" required/> I agree to the privacy notice.</label><input className="hp" name="honeypot" tabIndex={-1} autoComplete="off"/><button className="button primary" type="submit">Send message →</button></form></div></section>
    if (block.blockType === 'faq') return <section className="section" key={key}><div className="shell"><h2>{block.heading}</h2><div className="faqs">{block.manualItems?.map((item:any,i:number)=><details key={i}><summary>{item.question}</summary><p>{item.answer}</p></details>)}</div></div></section>
    return null
  })}</>
}
