export const articles = [
  { slug: 'choosing-your-first-ai-workflow', title: 'How to choose your first AI workflow', description: 'A practical starting point for choosing a bounded automation task, defining its inputs and keeping a person responsible for the outcome.', sections: [
    {title:'Start with repeatable work.',body:'Choose a task that happens often, has recognisable inputs and produces an output someone can check. Sorting incoming enquiries, preparing a research brief or drafting catalogue descriptions are clearer starting points than asking an agent to run an entire business.'},
    {title:'Describe a useful result.',body:'Write down what the output must contain, what it must avoid and how a reviewer will know it is useful. For an enquiry workflow, that might mean preserving the original message, identifying the request type and assigning a next owner without inventing a commercial promise.'},
    {title:'Map the access boundary.',body:'List the information and tools needed for the task. Separate reading information, preparing a recommendation and making an external change. Give the workflow only the access required for its current stage.'},
    {title:'Test the exceptions.',body:'Include incomplete requests, ambiguous wording, invalid inputs and service failures. A useful system must show when it needs help. Keep a recovery path for work that fails partway through.'},
    {title:'Expand after review.',body:'Review real examples with the people who own the process. Improve the instructions, integration or acceptance criteria before broadening the task. A working pilot is evidence about that workflow, not proof that every business function can run autonomously.'},
  ]},
  { slug: 'clear-service-pages-for-search-and-ai', title: 'What makes a service page useful for search and AI answers?', description: 'Clear answers, meaningful structure and accurate claims help visitors understand a service and give search systems useful information to retrieve.', sections: [
    {title:'Answer the buyer’s question first.',body:'Say what the service does, who it is for and what a typical engagement includes. Explain the inputs, outputs and boundaries before asking someone to contact you. A list of technology names does not explain an outcome.'},
    {title:'Give each page a distinct purpose.',body:'A service overview, an industry application and a product page answer different questions. Connect them with descriptive links. Avoid creating many near-identical pages whose only difference is a location or keyword.'},
    {title:'Make the content accessible.',body:'Use readable headings, descriptive page titles, concise summaries and links that work without an interaction. Keep important text in the page itself. Structured data should describe the visible content, with no invented ratings, offers or customer claims.'},
    {title:'Treat AI discovery as part of search.',body:'Google’s guidance connects visibility in its generative AI search features to a crawlable site and useful, reliable content. Special wording cannot guarantee an AI citation or a search position. Keep improving the page for the people it is meant to help.'},
  ]},
] as const
