export const services = [
  { slug: 'research-strategy', title: 'Research & business strategy', summary: 'Background research, market intelligence and opportunity analysis to support clearer decisions.', tasks: ['Market and competitor research with source records', 'Customer and audience research synthesis', 'Business-model and opportunity assessment', 'Product discovery and prioritised recommendations'], inputs: 'Your business question, target market, existing research and the decision you need to make.', output: 'A source-backed research brief, comparison framework and prioritised next steps.', boundaries: 'Research supports a decision. Findings need human review and are limited by the quality and availability of source material.', agents: ['lumina', 'aether-rahm'] },
  { slug: 'marketing-growth', title: 'Marketing strategy & campaign execution', summary: 'Connect audience understanding, positioning, campaign planning and day-to-day marketing work.', tasks: ['Audience, positioning and campaign strategy', 'Content calendars and creative briefs', 'Campaign assets, landing pages and email drafts', 'Performance review and experiment planning'], inputs: 'Brand guidelines, audience, offer, channels, budget boundaries and approved account access.', output: 'A campaign plan, reviewed assets and an execution workflow with clear ownership.', boundaries: 'Publishing, paid spend and account actions require approved access and agreed authority. Results are measured; returns are not guaranteed.', agents: ['idris-pulse', 'amara-prism', 'yara-halo'] },
  { slug: 'seo-aeo', title: 'SEO, AEO & content systems', summary: 'Make useful content easier for people, search engines and AI answer systems to understand.', tasks: ['Technical and on-page SEO audits', 'Search intent and topic research', 'Clear service pages, internal links and structured data', 'Editorial briefs, content updates and performance review'], inputs: 'Your website, target audiences, services, markets and access to any existing search performance data.', output: 'A prioritised search plan, content structure and measurable implementation backlog.', boundaries: 'Search visibility cannot be guaranteed. We focus on useful source-backed content and sound technical foundations.', agents: ['idris-pulse', 'lumina', 'amara-prism'] },
  { slug: 'website-development', title: 'Website design & development', summary: 'Plan, design and build readable, responsive websites around a clear business purpose.', tasks: ['Information architecture and content planning', 'Frontend design and responsive development', 'CMS setup, backend forms and integrations', 'Accessibility, performance and release checks'], inputs: 'Your goals, audience, brand assets, content requirements and current systems.', output: 'A website implementation with content ownership, validation and handover requirements defined.', boundaries: 'Hosting, migration, third-party services and ongoing maintenance are scoped explicitly.', agents: ['amara-prism', 'kai-vector', 'leila-orbit'] },
  { slug: 'application-development', title: 'Application & backend development', summary: 'Build web applications, internal tools and APIs that connect customer experiences to business operations.', tasks: ['Product requirements and user journeys', 'Frontend and backend application development', 'Database, authentication and API integration', 'Testing, deployment and support planning'], inputs: 'User needs, workflow rules, data sources, security requirements and integration constraints.', output: 'A defined product increment with documented interfaces, acceptance checks and operational handover.', boundaries: 'Technology, delivery scope and supported platforms are agreed during discovery. AI-assisted engineering still requires review and testing.', agents: ['kai-vector', 'amara-prism', 'mikhail-sentinel'] },
  { slug: 'ai-automation', title: 'AI development & workflow automation', summary: 'Apply AI to repetitive work, knowledge retrieval and decision support with explicit boundaries.', tasks: ['Workflow mapping and automation suitability assessment', 'AI assistants and knowledge-grounded experiences', 'Tool, API and business-system integrations', 'Human approvals, exception handling and evaluation'], inputs: 'A defined task, representative examples, authorised data and acceptable failure boundaries.', output: 'A bounded automation workflow with verification, escalation and monitoring requirements.', boundaries: 'Agent capabilities depend on tools, permissions and validation. Open-ended autonomous operation is not assumed.', agents: ['kai-vector', 'aether-rahm', 'mikhail-sentinel'] },
  { slug: 'sales-customer-operations', title: 'Sales & customer operations', summary: 'Support the work around lead qualification, sales preparation, onboarding and customer follow-up.', tasks: ['Enquiry classification and lead qualification', 'Discovery preparation and proposal drafts', 'CRM workflow and customer-context organisation', 'Onboarding materials, support triage and follow-up preparation'], inputs: 'Your offer, qualification rules, CRM process and approved customer information.', output: 'An organised pipeline workflow, clear handoffs and reviewed customer-facing materials.', boundaries: 'Pricing, contracts, commitments and sensitive customer communication remain subject to authorised human decisions.', agents: ['yara-halo', 'mei-nova', 'esme-echo'] },
  { slug: 'infrastructure-operations', title: 'Infrastructure & managed operations', summary: 'Plan the systems, operating procedures and visibility needed to keep digital work dependable.', tasks: ['Infrastructure and dependency assessment', 'Deployment, backup and recovery planning', 'Operational workflow and runbook development', 'Monitoring requirements and controlled change processes'], inputs: 'Your systems, access boundaries, operating responsibilities and service requirements.', output: 'An operational plan and scoped implementation with clear owners and recovery procedures.', boundaries: 'Service hours, response commitments and managed access require a separate agreement. No uptime or certification is implied.', agents: ['mikhail-sentinel', 'leila-orbit', 'kai-vector'] },
] as const

export const industries = [
  { slug: 'retail-ecommerce', title: 'Retail & ecommerce', workflow: 'Product information, catalogue updates, customer questions and merchant operations.', examples: ['Catalogue and content workflows', 'Customer enquiry routing', 'Commerce integrations and reporting'] },
  { slug: 'professional-services', title: 'Professional services', workflow: 'Research, proposals, client onboarding and knowledge-intensive delivery.', examples: ['Research and proposal preparation', 'Internal knowledge assistants', 'Client intake and delivery workflows'] },
  { slug: 'technology-saas', title: 'Technology & SaaS', workflow: 'Product development, technical content, customer onboarding and infrastructure operations.', examples: ['Application and API development', 'Product documentation and content systems', 'Support triage and operational tooling'] },
  { slug: 'hospitality-travel', title: 'Hospitality & travel', workflow: 'Guest information, service enquiries, marketing content and operational coordination.', examples: ['Guest information and enquiry workflows', 'Content and campaign production', 'Booking-system integration planning'] },
  { slug: 'real-estate-construction', title: 'Real estate & construction', workflow: 'Project information, listing content, enquiries and coordination between teams.', examples: ['Listing and project content', 'Lead qualification workflows', 'Project documentation and reporting tools'] },
  { slug: 'education-training', title: 'Education & training', workflow: 'Course information, learning operations, administrative support and content organisation.', examples: ['Course and programme content', 'Enquiry and administrative workflows', 'Knowledge and learning-platform integrations'] },
  { slug: 'manufacturing-logistics', title: 'Manufacturing & logistics', workflow: 'Operational records, reporting, internal knowledge and coordination across business systems.', examples: ['Document and knowledge organisation', 'Operational reporting tools', 'System integration and exception workflows'] },
  { slug: 'agencies-startups', title: 'Agencies & startups', workflow: 'Market research, product validation, campaign delivery and repeatable client work.', examples: ['Research and product discovery', 'Websites, applications and launch content', 'Internal tools and delivery automation'] },
] as const

export const regions = [
  { slug: 'australia', title: 'Australia', focus: 'Digital service delivery, commerce workflows and collaboration planned around Australian time zones.' },
  { slug: 'united-states', title: 'United States', focus: 'Product development, business automation and marketing delivery planned for US audiences and working hours.' },
  { slug: 'europe', title: 'Europe', focus: 'Business platforms and digital services shaped around the intended country, language and operating requirements.' },
  { slug: 'gulf', title: 'The Gulf', focus: 'Business websites, commerce experiences and multilingual content requirements scoped for Gulf markets.' },
  { slug: 'asia', title: 'Asia', focus: 'Digital services and connected business systems tailored to the target market, languages and delivery context.' },
] as const

export const cataloguePages = [
  { slug: 'industries', eyebrow: 'Industries & sectors', title: 'Start with the way your industry works.', description: 'Apply research, engineering, marketing and automation to a specific operating context. These are service applications, not claims of customer deployments.', sections: [] },
  { slug: 'locations', eyebrow: 'Regions & remote delivery', title: 'Local context. Connected delivery.', description: 'Afluma targets Australia, the United States, Europe, the Gulf and Asia. Engagement availability and local requirements are confirmed during discovery.', sections: [{title:'Plan for the market.',body:'Audience, language, working hours, data handling and local requirements shape the engagement. A regional page describes a target market; it does not imply an office, local legal entity or regulatory certification.'}] },
  ...services.map((service) => ({slug:`services/${service.slug}`,eyebrow:'Afluma services',title:service.title,description:service.summary,sections:[{title:'What the work can include',body:'The engagement is scoped around the outcome you need.',items:[...service.tasks]},{title:'What we need to begin',body:service.inputs},{title:'What you receive',body:service.output},{title:'Delivery boundaries',body:service.boundaries}]})),
  ...industries.map((industry) => ({slug:`industries/${industry.slug}`,eyebrow:'Industry applications',title:industry.title,description:industry.workflow,sections:[{title:'Practical starting points',body:'Begin with one defined workflow and the information required to improve it.',items:[...industry.examples]},{title:'Designed for your operating context',body:'We assess the people, data, systems and approvals involved before selecting an implementation. Sensitive or regulated decisions remain with qualified, authorised people.'}]})),
  ...regions.map((region) => ({slug:`locations/${region.slug}`,eyebrow:'Target market',title:`Afluma for ${region.title}`,description:region.focus,sections:[{title:'A practical remote engagement',body:'Research, product engineering, marketing and automation can be coordinated through an agreed delivery process. Scope, availability, language and working hours are confirmed before an engagement begins.'},{title:'Requirements before promises',body:'Data handling, contractual terms, local rules and deployment choices depend on the project. This target-market page does not claim a local office or existing customer results.'}]})),
]
